title: Ridmi Imasha
log: /assets/profile_photo.jpg
description: As an inquisitive and highly motivated undergraduate in Biotechnology, I aspire to pursue a career as an academic and researcher in the field of Molecular Life Sciences.
theme: jekyll-theme-minimal
